language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

before_install:
  - curl -s http://snowball.tartarus.org/dist/libstemmer_c.tgz | tar xzf -
  - pip install --use-mirrors Cython

install: python setup.py install

before_script: pip install --use-mirrors nose

script:
  - python runtests.py -v
  - nosetests -v

